#!/usr/bin/env python3
"""
Generates apps/web/src/components/seal-glyphs.ts: SVG outlines of the kanji drawn on pack seals,
from Noto Serif CJK JP Bold (SIL Open Font License), fitted in a 40-unit box centered in the
64-unit seal. Usage: python3 scripts/seal-glyphs.py [font.ttc] > apps/web/src/components/seal-glyphs.ts
Requires fontTools (pip install fonttools). Kanji without an outline are drawn as text.
"""
import sys
from fontTools.ttLib import TTCollection
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.pens.boundsPen import BoundsPen
FONT = sys.argv[1] if len(sys.argv) > 1 else "/usr/share/fonts/noto-cjk/NotoSerifCJK-Bold.ttc"
GLYPHS = "招少姫青競艶女男動遊"
coll = TTCollection(FONT)
font = next(f for f in coll.fonts if 'JP' in f['name'].getDebugName(1))
cmap = font.getBestCmap(); gs = font.getGlyphSet()
def path(ch, box=40, center=32):
    g = gs[cmap[ord(ch)]]
    bp = BoundsPen(gs); g.draw(bp)
    x0, y0, x1, y1 = bp.bounds
    s = box / max(x1 - x0, y1 - y0)
    ox = center - (x0 + x1) / 2 * s
    oy = center + (y0 + y1) / 2 * s
    pen = SVGPathPen(gs, ntos=lambda v: ('%.2f' % v).rstrip('0').rstrip('.'))
    g.draw(TransformPen(pen, (s, 0, 0, -s, ox, oy)))
    return pen.getCommands()
print("// Generated by scripts/seal-glyphs.py from Noto Serif CJK JP Bold (SIL OFL 1.1). Do not edit.")
print("")
print("/** SVG path (64-unit seal viewBox) of each kanji with a built-in outline. */")
print("export const SEAL_GLYPHS: Record<string, string> = {")
for ch in GLYPHS:
    print(f"  '{ch}':\n    '{path(ch)}',")
print("}")
